name: PublishForCICD
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
env: 
AZURE_WEBAPP_NAME: apptestdemo
AZURE_WEBAPP_PACKAGE_PATH: ./publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./githubdemo.csproj
      - name: Build
        run: dotnet build ./githubdemo.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./githubdemo.csproj -c Release -o ./publish
      - name: deployment
        uses: azure/webapps-deploy@v2
        with: null
        app-name: '${{ env.AZURE_WEBAPP_NAME }}'
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
